language: scala
branches:
  only:
    - master
script:
  - sbt test coverageReport
jdk: oraclejdk8
after_success:
  - 'bash <(curl -s https://codecov.io/bash)'
  - 'if [[ $TRAVIS_PULL_REQUEST == "false" ]]; then bash ./deploy.sh; fi'
